//back-end/src/database/Game Information/board-layout-level1.ts
export const level1Layout: string[] = [
    "Opportunity",
    "Invest in Yourself",
    "Opportunity",
    "Payday",
    "Opportunity",
    "Luxury",
    "Opportunity",
    "Market",
    "Opportunity",
    "Life Event",
    "Opportunity",
    "Invest in Yourself",
    "Opportunity",
    "Payday",
    "Opportunity",
    "Luxury",
    "Opportunity",
    "Market",
    "Opportunity",
    "Life Event",
    "Opportunity",
    "Invest in Yourself",
    "Opportunity",
    "Payday",
    "Opportunity",
    "Luxury",
    "Opportunity",
    "Market",
    "Opportunity",
    "Charity"
];